"""add_frozen_state

Revision ID: 2c08a17a93dc
Revises: 2f7e7f4c81a3
Create Date: 2026-04-21 21:23:20.386767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2c08a17a93dc"
down_revision: Union[str, Sequence[str], None] = "2f7e7f4c81a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "licences", sa.Column("is_frozen", sa.Boolean(),server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("licences", "is_frozen")
    # ### end Alembic commands ###
